<a href="https://colab.research.google.com/github/carlosfmorenog/CM4125/blob/main/T04/CM4125_Lec4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CM4125 Topic 4 - Data Loading and Exploration

## Lecture objectives

1) Understand how we define data (for the purpose of this module) and where to get it

2) Learn different methods to import/export data into practical representations

3) Apply basic commands and concepts to explore it

## What is data (for data viz purposes)?

Information or characteristics collected through observation or experimentation

Using a tabular approach...

Each entry/observation corresponds to a `row`

Each feature/characteristic corresponds to a `column`

## Where to get data from?

### "From a friend"

We are given access to a file or register containing the data

There are many formats, but mostly we will deal with:

    .csv
    .tsv
    .txt
    .xlsx
    .json

In [ ]:
## Example: Reading a .csv file into python
## This file contains the age and height of some participants
import pandas as pd
df = pd.read_csv('https://www.dropbox.com/scl/fi/rjxj1fyvyt7ngwrim89d8/data.csv?rlkey=436xq62tyk248xxssneuzzkmu&raw=1')
df

       Col 1  Col 2  Col 3
0       Nick     21   1.85
1      Chris     29   1.79
2        Tim     28   1.75
3        Ron     34   1.81
4     Monica     35   1.69
5  Cassandra     21   1.66

### Online repos

* There is a huge amount of free data out there!
* Just be careful where you get it!
* Websites such as [Kaggle](https://www.kaggle.com), [UCI](https://archive.ics.uci.edu/ml/index.php) or [Keel](https://sci2s.ugr.es/keel/datasets.php) contain thousands of examples that you can download and import to your preferred tool
* Sometimes they even contain ways to connect to your data in faster and more secure ways

![Fig. 1](https://www.dropbox.com/scl/fi/1uk8k3tilgispby1mijdc/fig2.jpg?rlkey=1ejvfxz9gzuk6ol2dykazjd4y&raw=1)

### Modules and packages

Languages such as Python and R already contain some preloaded data repositories

They are sometimes in weird shapes and forms

Nonetheless, they are good to start experimenting!

In [ ]:
## Loading the IRIS dataset from the SCIKIT LEARN module
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

## Exploring Data by Rows

Now that we have data in a tabular form, let's see how to access certain positions

To do so, let's use a larger dataset of Netflix Original series contained in a .csv file called `netflix.csv`

In [ ]:
netflix = pd.read_csv('https://www.dropbox.com/scl/fi/xo9zepvclpfe76fzwcwlg/netflix.csv?rlkey=g7q3k91p0lzz2jkznr7hid2fc&raw=1')
netflix

,Title,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
0,House of Cards,Political drama,"political,drama",1-Feb-13,"6 seasons, 73 episodes",6,73,42–59 min.,42,59,Ended,0,Drama,English
1,Hemlock Grove,Horror/thriller,"horror,thriller",19-Apr-13,"3 seasons, 33 episodes",3,33,45–58 min.,45,58,Ended,0,Drama,English
2,Orange Is the New Black,Comedy-drama,comedy-drama,11-Jul-13,"6 seasons, 78 episodes",6,78,50–92 min.,50,92,Renewed,1,Drama,English
3,Marco Polo,Historical drama,"historical,drama",12-Dec-14,"2 seasons, 20 episodes",2,20,48–65 min.,48,65,Ended,0,Drama,English
4,Bloodline,Thriller,thriller,20-Mar-15,"3 seasons, 33 episodes",3,33,48–68 min.,48,68,Ended,0,Drama,English
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,Busted!,Korean language variety show,"korean,language,variety,show",4-May-18,"1 season, 10 episodes",1,10,75–98 min.,75,98,Renewed,1,VarietyTalk,Korean
354,The Break with Michelle Wolf,Late-night,late-night,27-May-18,"1 season, 10 episodes",1,10,27 min.,27,27,Renewed,1,VarietyTalk,English
355,Norm Macdonald Has a Show,Talk show,"talk,show",14-Sep-18,"1 season, 10 episodes",1,10,26–35 min.,26,35,Pending,1,VarietyTalk,English
356,Patriot Act with Hasan Minhaj,Talk show,"talk,show",28-Oct-18,"3 volumes, 19 episodes",0,19,23–30 min.,23,30,Renewed,1,VarietyTalk,English
357,The Fix,Panel show,"panel,show",14-Dec-18,"1 season, 10 episodes",1,10,23–31 min.,23,31,Pending,1,VarietyTalk,English

Notice that when the `DataFrame` is shown in Jupyter, it displays `358 rows × 14 columns` at the bottom to tell us how large the dataset is.

### Using a Non-Numerical Index

We can actually use any of the unique-entry columns (for example `Title`, which is column `0`)

In [ ]:
# reloading the dataset, now stating the first column as the index one
netflix = pd.read_csv('https://www.dropbox.com/scl/fi/xo9zepvclpfe76fzwcwlg/netflix.csv?rlkey=g7q3k91p0lzz2jkznr7hid2fc&raw=1',
                      index_col=0)
netflix

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
House of Cards,Political drama,"political,drama",1-Feb-13,"6 seasons, 73 episodes",6,73,42–59 min.,42,59,Ended,0,Drama,English
Hemlock Grove,Horror/thriller,"horror,thriller",19-Apr-13,"3 seasons, 33 episodes",3,33,45–58 min.,45,58,Ended,0,Drama,English
Orange Is the New Black,Comedy-drama,comedy-drama,11-Jul-13,"6 seasons, 78 episodes",6,78,50–92 min.,50,92,Renewed,1,Drama,English
Marco Polo,Historical drama,"historical,drama",12-Dec-14,"2 seasons, 20 episodes",2,20,48–65 min.,48,65,Ended,0,Drama,English
Bloodline,Thriller,thriller,20-Mar-15,"3 seasons, 33 episodes",3,33,48–68 min.,48,68,Ended,0,Drama,English
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Busted!,Korean language variety show,"korean,language,variety,show",4-May-18,"1 season, 10 episodes",1,10,75–98 min.,75,98,Renewed,1,VarietyTalk,Korean
The Break with Michelle Wolf,Late-night,late-night,27-May-18,"1 season, 10 episodes",1,10,27 min.,27,27,Renewed,1,VarietyTalk,English
Norm Macdonald Has a Show,Talk show,"talk,show",14-Sep-18,"1 season, 10 episodes",1,10,26–35 min.,26,35,Pending,1,VarietyTalk,English
Patriot Act with Hasan Minhaj,Talk show,"talk,show",28-Oct-18,"3 volumes, 19 episodes",0,19,23–30 min.,23,30,Renewed,1,VarietyTalk,English
The Fix,Panel show,"panel,show",14-Dec-18,"1 season, 10 episodes",1,10,23–31 min.,23,31,Pending,1,VarietyTalk,English

It's up to you to decide whether to use default numerical indexing or to use an uniquely-identifying column from your dataset.

### Locating an item

In [ ]:
# Locating all info of an entry
netflix.loc['Orange Is the New Black']

Genre                       Comedy-drama
GenreLabels                 comedy-drama
Premiere                       11-Jul-13
Seasons           6 seasons, 78 episodes
SeasonsParsed                          6
EpisodesParsed                        78
Length                        50–92 min.
MinLength                             50
MaxLength                             92
Status                           Renewed
Active                                 1
Table                              Drama
Language                         English
Name: Orange Is the New Black, dtype: object

In [ ]:
# Locating particular info of that entry
netflix.at['Orange Is the New Black', 'Seasons']

'6 seasons, 78 episodes'

In [ ]:
# This one allows you to access by number, even if the table has no numerical indexes
netflix.iloc[0]

Genre                    Political drama
GenreLabels              political,drama
Premiere                        1-Feb-13
Seasons           6 seasons, 73 episodes
SeasonsParsed                          6
EpisodesParsed                        73
Length                        42–59 min.
MinLength                             42
MaxLength                             59
Status                             Ended
Active                                 0
Table                              Drama
Language                         English
Name: House of Cards, dtype: object

### Getting a Subset of the Data

In [ ]:
netflix.head(5)

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
House of Cards,Political drama,"political,drama",1-Feb-13,"6 seasons, 73 episodes",6,73,42–59 min.,42,59,Ended,0,Drama,English
Hemlock Grove,Horror/thriller,"horror,thriller",19-Apr-13,"3 seasons, 33 episodes",3,33,45–58 min.,45,58,Ended,0,Drama,English
Orange Is the New Black,Comedy-drama,comedy-drama,11-Jul-13,"6 seasons, 78 episodes",6,78,50–92 min.,50,92,Renewed,1,Drama,English
Marco Polo,Historical drama,"historical,drama",12-Dec-14,"2 seasons, 20 episodes",2,20,48–65 min.,48,65,Ended,0,Drama,English
Bloodline,Thriller,thriller,20-Mar-15,"3 seasons, 33 episodes",3,33,48–68 min.,48,68,Ended,0,Drama,English

In [ ]:
netflix.tail(3)

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Norm Macdonald Has a Show,Talk show,"talk,show",14-Sep-18,"1 season, 10 episodes",1,10,26–35 min.,26,35,Pending,1,VarietyTalk,English
Patriot Act with Hasan Minhaj,Talk show,"talk,show",28-Oct-18,"3 volumes, 19 episodes",0,19,23–30 min.,23,30,Renewed,1,VarietyTalk,English
The Fix,Panel show,"panel,show",14-Dec-18,"1 season, 10 episodes",1,10,23–31 min.,23,31,Pending,1,VarietyTalk,English

In [ ]:
netflix.sample(5)

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Shadow,Thriller,thriller,8-Mar-19,"1 season, 8 episodes",1,8,40–49 min.,40,49,Pending,1,Drama,English
Our Planet,Nature documentary,"nature,documentary",5-Apr-19,8 episodes,0,8,49–54 min.,49,54,Miniseries,0,DocuSeries,English
Marching Orders,Docu-series,docu-series,3-Aug-18,"1 season, 12 episodes",1,12,9–14 min.,9,14,Pending,1,DocuSeries,English
FightWorld,Travel documentary,"travel,documentary",12-Oct-18,"1 season, 5 episodes",1,5,41–44 min.,41,44,Pending,1,DocuSeries,English
Bloodline,Thriller,thriller,20-Mar-15,"3 seasons, 33 episodes",3,33,48–68 min.,48,68,Ended,0,Drama,English

### Choosing Specific Rows

In [ ]:
netflix.loc[['Diablero', 'Motown Magic', 'Typewriter']] # by index

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Diablero,Horror fantasy thriller,"horror,fantasy,thriller",21-Dec-18,"1 season, 8 episodes",1,8,36–44 min.,36,44,Renewed,1,ForeignLanguage,Spanish
Motown Magic,childrens-animation,childrens-animation,20-Nov-18,"1 season, 25 episodes",1,25,15–26 min.,15,26,Renewed,1,Children,English
Typewriter,Horror,horror,19-Jul-19,TBA,0,0,TBA,0,0,Pending,1,ForeignLanguage,Hindi

In [ ]:
netflix.iloc[[40, 12, 106, 79]] # by numerical index

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Jessica Jones,Neo-noir/psychological thriller,"neo-noir,psychological,thriller",20-Nov-15,"3 seasons, 39 episodes",3,39,44–56 min.,44,56,Ended,0,Marvel,English
A Series of Unfortunate Events,Black-comedy mystery,"black-comedy,mystery",13-Jan-17,"3 seasons, 25 episodes",3,25,36–64 min.,36,64,Ended,0,Drama,English
Lost Song,Musical fantasy,"musical,fantasy",31-Mar-18,"1 season, 12 episodes",1,12,23–24 min.,23,24,Ended,0,Anime,English
After Life,Comedy,comedy,8-Mar-19,"1 season, 6 episodes",1,6,25–31 min.,25,31,Renewed,1,Comedy,English

In [ ]:
netflix.loc['Maniac':'After Life'] # selecting a range by index

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Maniac,Dark comedy,"dark,comedy",21-Sep-18,10 episodes,0,10,27–47 min.,27,47,Miniseries,0,Comedy,English
The Kominsky Method,Comedy,comedy,16-Nov-18,"1 season, 8 episodes",1,8,23–34 min.,23,34,Renewed,1,Comedy,English
Sex Education,Coming-of-age comedy-drama,"coming-of-age,comedy-drama",11-Jan-19,"1 season, 8 episodes",1,8,47–53 min.,47,53,Renewed,1,Comedy,English
Russian Doll,Comedy,comedy,1-Feb-19,"1 season, 8 episodes",1,8,25–30 min.,25,30,Renewed,1,Comedy,English
After Life,Comedy,comedy,8-Mar-19,"1 season, 6 episodes",1,6,25–31 min.,25,31,Renewed,1,Comedy,English

In [ ]:
netflix.iloc[75:79] # selecting a range by numerical index

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Maniac,Dark comedy,"dark,comedy",21-Sep-18,10 episodes,0,10,27–47 min.,27,47,Miniseries,0,Comedy,English
The Kominsky Method,Comedy,comedy,16-Nov-18,"1 season, 8 episodes",1,8,23–34 min.,23,34,Renewed,1,Comedy,English
Sex Education,Coming-of-age comedy-drama,"coming-of-age,comedy-drama",11-Jan-19,"1 season, 8 episodes",1,8,47–53 min.,47,53,Renewed,1,Comedy,English
Russian Doll,Comedy,comedy,1-Feb-19,"1 season, 8 episodes",1,8,25–30 min.,25,30,Renewed,1,Comedy,English

### Filtering Rows by Values in Columns

One of the most important features you need is to be able to filter observations out

We can define a **condition** so that it can be checked for all entries

In [ ]:
our_condition = netflix['SeasonsParsed'] == 6
our_condition

Title
House of Cards                    True
Hemlock Grove                    False
Orange Is the New Black           True
Marco Polo                       False
Bloodline                        False
                                 ...
Busted!                          False
The Break with Michelle Wolf     False
Norm Macdonald Has a Show        False
Patriot Act with Hasan Minhaj    False
The Fix                          False
Name: SeasonsParsed, Length: 358, dtype: bool

Then, we can ask for that condition to be the filter of the original dataset

In [ ]:
netflix[our_condition]

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
House of Cards,Political drama,"political,drama",1-Feb-13,"6 seasons, 73 episodes",6,73,42–59 min.,42,59,Ended,0,Drama,English
Orange Is the New Black,Comedy-drama,comedy-drama,11-Jul-13,"6 seasons, 78 episodes",6,78,50–92 min.,50,92,Renewed,1,Drama,English
The Adventures of Puss in Boots,childrens-animation,childrens-animation,16-Jan-15,"6 seasons, 78 episodes",6,78,22–24 min.,22,24,Ended,0,Children,English
Dragons: Race to the Edge,childrens-animation,childrens-animation,26-Jun-15,"6 seasons, 78 episodes",6,78,22–23 min.,22,23,Ended,0,Children,English
Trolls: The Beat Goes On!,childrens-animation,childrens-animation,19-Jan-18,"6 seasons, 38 episodes",6,38,24–25 min.,24,25,Pending,1,Children,English

In [ ]:
netflix[netflix['SeasonsParsed'] == 6] # the same, but in one line

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
House of Cards,Political drama,"political,drama",1-Feb-13,"6 seasons, 73 episodes",6,73,42–59 min.,42,59,Ended,0,Drama,English
Orange Is the New Black,Comedy-drama,comedy-drama,11-Jul-13,"6 seasons, 78 episodes",6,78,50–92 min.,50,92,Renewed,1,Drama,English
The Adventures of Puss in Boots,childrens-animation,childrens-animation,16-Jan-15,"6 seasons, 78 episodes",6,78,22–24 min.,22,24,Ended,0,Children,English
Dragons: Race to the Edge,childrens-animation,childrens-animation,26-Jun-15,"6 seasons, 78 episodes",6,78,22–23 min.,22,23,Ended,0,Children,English
Trolls: The Beat Goes On!,childrens-animation,childrens-animation,19-Jan-18,"6 seasons, 38 episodes",6,38,24–25 min.,24,25,Pending,1,Children,English

In [ ]:
netflix[netflix['MaxLength'] > 100] # series longer than 100 minutes

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Sense8,Science fiction,science-fiction,5-Jun-15,"2 seasons, 24 episodes",2,24,45–152 min.,45,152,Ended,0,Drama,English
Gilmore Girls: A Year in the Life,Family drama,"family,drama",25-Nov-16,4 episodes,0,4,88–102 min.,88,102,Miniseries,0,Drama,English

In [ ]:
# series with a number of episodes between 30 and 34
netflix[(netflix['EpisodesParsed'] >= 30) & (netflix['EpisodesParsed'] < 35)]

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Hemlock Grove,Horror/thriller,"horror,thriller",19-Apr-13,"3 seasons, 33 episodes",3,33,45–58 min.,45,58,Ended,0,Drama,English
Bloodline,Thriller,thriller,20-Mar-15,"3 seasons, 33 episodes",3,33,48–68 min.,48,68,Ended,0,Drama,English
Narcos,Crime drama,"crime,drama",28-Aug-15,"3 seasons, 30 episodes",3,30,43–60 min.,43,60,Ended,0,Drama,English
Love,Romantic comedy,"romantic,comedy",19-Feb-16,"3 seasons, 34 episodes",3,34,24–40 min.,24,40,Ended,0,Comedy,English
Santa Clarita Diet,Comedy-horror,comedy-horror,3-Feb-17,"3 seasons, 30 episodes",3,30,26–35 min.,26,35,Ended,0,Comedy,English
Go! Live Your Way,Musical,musical,22-Feb-19,"2 seasons, 30 episodes",2,30,36–44 min.,36,44,Pending,1,ForeignLanguage,Spanish
Chef's Table,Culinary art,"culinary,art",26-Apr-15,"6 volumes, 30 episodes",0,30,42–58 min.,42,58,Renewed,1,DocuSeries,English

In [ ]:
# with 33 or 73 episodes
netflix[(netflix['EpisodesParsed'] == 33) | (netflix['EpisodesParsed'] == 73)]

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
House of Cards,Political drama,"political,drama",1-Feb-13,"6 seasons, 73 episodes",6,73,42–59 min.,42,59,Ended,0,Drama,English
Hemlock Grove,Horror/thriller,"horror,thriller",19-Apr-13,"3 seasons, 33 episodes",3,33,45–58 min.,45,58,Ended,0,Drama,English
Bloodline,Thriller,thriller,20-Mar-15,"3 seasons, 33 episodes",3,33,48–68 min.,48,68,Ended,0,Drama,English

###  Sorting Rows

Let's create a new dataframe called `variable_length_shows` that contains series where longest episode is 45 minutes longer than the shortest

In [ ]:
variable_length_shows = netflix[netflix['MaxLength'] > netflix['MinLength'] + 45]
variable_length_shows

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Sense8,Science fiction,science-fiction,5-Jun-15,"2 seasons, 24 episodes",2,24,45–152 min.,45,152,Ended,0,Drama,English
Kong: King of the Apes,childrens-animation,childrens-animation,15-Apr-16,"2 seasons, 23 episodes",2,23,22–85 min.,22,85,Ended,0,Children,English
Club de Cuervos,Comedy-drama,comedy-drama,7-Aug-15,"4 seasons, 45 episodes",4,45,36–94 min.,36,94,Ended,0,ForeignLanguage,Spanish

We can use the `sort_values` method to sort on a chosen variable.

In [ ]:
variable_length_shows.sort_values('MaxLength')

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Kong: King of the Apes,childrens-animation,childrens-animation,15-Apr-16,"2 seasons, 23 episodes",2,23,22–85 min.,22,85,Ended,0,Children,English
Club de Cuervos,Comedy-drama,comedy-drama,7-Aug-15,"4 seasons, 45 episodes",4,45,36–94 min.,36,94,Ended,0,ForeignLanguage,Spanish
Sense8,Science fiction,science-fiction,5-Jun-15,"2 seasons, 24 episodes",2,24,45–152 min.,45,152,Ended,0,Drama,English

We can also sort in reverse (descending) order using `ascending=False`.

In [ ]:
variable_length_shows.sort_values('MaxLength', ascending=False)

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Sense8,Science fiction,science-fiction,5-Jun-15,"2 seasons, 24 episodes",2,24,45–152 min.,45,152,Ended,0,Drama,English
Club de Cuervos,Comedy-drama,comedy-drama,7-Aug-15,"4 seasons, 45 episodes",4,45,36–94 min.,36,94,Ended,0,ForeignLanguage,Spanish
Kong: King of the Apes,childrens-animation,childrens-animation,15-Apr-16,"2 seasons, 23 episodes",2,23,22–85 min.,22,85,Ended,0,Children,English

Note that `sort_values` does **not** actually modify the contents of the data frame!

If we use the ascendig order, we will see it is not sorted!

In [ ]:
variable_length_shows.sort_values('MaxLength')
variable_length_shows

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Sense8,Science fiction,science-fiction,5-Jun-15,"2 seasons, 24 episodes",2,24,45–152 min.,45,152,Ended,0,Drama,English
Kong: King of the Apes,childrens-animation,childrens-animation,15-Apr-16,"2 seasons, 23 episodes",2,23,22–85 min.,22,85,Ended,0,Children,English
Club de Cuervos,Comedy-drama,comedy-drama,7-Aug-15,"4 seasons, 45 episodes",4,45,36–94 min.,36,94,Ended,0,ForeignLanguage,Spanish

Solution: Create a new variable!

In [ ]:
new = variable_length_shows.sort_values('MaxLength')
new

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language
Title,,,,,,,,,,,,,
Kong: King of the Apes,childrens-animation,childrens-animation,15-Apr-16,"2 seasons, 23 episodes",2,23,22–85 min.,22,85,Ended,0,Children,English
Club de Cuervos,Comedy-drama,comedy-drama,7-Aug-15,"4 seasons, 45 episodes",4,45,36–94 min.,36,94,Ended,0,ForeignLanguage,Spanish
Sense8,Science fiction,science-fiction,5-Jun-15,"2 seasons, 24 episodes",2,24,45–152 min.,45,152,Ended,0,Drama,English

Creating a new dataset only with certain columns

In [ ]:
shorter_netflix = netflix[['Genre', 'SeasonsParsed']]
shorter_netflix

                                                      Genre  SeasonsParsed
Title
House of Cards                              Political drama              6
Hemlock Grove                               Horror/thriller              3
Orange Is the New Black                        Comedy-drama              6
Marco Polo                                 Historical drama              2
Bloodline                                          Thriller              3
...                                                     ...            ...
Busted!                        Korean language variety show              1
The Break with Michelle Wolf                     Late-night              1
Norm Macdonald Has a Show                         Talk show              1
Patriot Act with Hasan Minhaj                     Talk show              0
The Fix                                          Panel show              1

[358 rows x 2 columns]

Adding new columns to a data frame (we will continue discussing this on the Data Manipulation Topic)

In [ ]:
# creating a new column named 'watched' filled with no
netflix['Watched'] = ['No']*len(netflix)
netflix

,Genre,GenreLabels,Premiere,Seasons,SeasonsParsed,EpisodesParsed,Length,MinLength,MaxLength,Status,Active,Table,Language,Watched
Title,,,,,,,,,,,,,,
House of Cards,Political drama,"political,drama",1-Feb-13,"6 seasons, 73 episodes",6,73,42–59 min.,42,59,Ended,0,Drama,English,No
Hemlock Grove,Horror/thriller,"horror,thriller",19-Apr-13,"3 seasons, 33 episodes",3,33,45–58 min.,45,58,Ended,0,Drama,English,No
Orange Is the New Black,Comedy-drama,comedy-drama,11-Jul-13,"6 seasons, 78 episodes",6,78,50–92 min.,50,92,Renewed,1,Drama,English,No
Marco Polo,Historical drama,"historical,drama",12-Dec-14,"2 seasons, 20 episodes",2,20,48–65 min.,48,65,Ended,0,Drama,English,No
Bloodline,Thriller,thriller,20-Mar-15,"3 seasons, 33 episodes",3,33,48–68 min.,48,68,Ended,0,Drama,English,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Busted!,Korean language variety show,"korean,language,variety,show",4-May-18,"1 season, 10 episodes",1,10,75–98 min.,75,98,Renewed,1,VarietyTalk,Korean,No
The Break with Michelle Wolf,Late-night,late-night,27-May-18,"1 season, 10 episodes",1,10,27 min.,27,27,Renewed,1,VarietyTalk,English,No
Norm Macdonald Has a Show,Talk show,"talk,show",14-Sep-18,"1 season, 10 episodes",1,10,26–35 min.,26,35,Pending,1,VarietyTalk,English,No
Patriot Act with Hasan Minhaj,Talk show,"talk,show",28-Oct-18,"3 volumes, 19 episodes",0,19,23–30 min.,23,30,Renewed,1,VarietyTalk,English,No
The Fix,Panel show,"panel,show",14-Dec-18,"1 season, 10 episodes",1,10,23–31 min.,23,31,Pending,1,VarietyTalk,English,No

## Finally
Talk about **harnessing the power of AI** in [Google Colab](https://colab.research.google.com/drive/1N_dbrOMHnmkoytVnv5ocNZ7d9eKv9lmy?usp=sharing)!

* Generating code (e.g. remove all columns except Watched)
* View recommended plots (histograms, scatters, comparisons between data)
* New interactive sheet (asks for access to lots of things, runs better in Chrome, in Firefox it behaves weird)
* Convert to interactive table and suggest charts from there, clear output to return

## Lab Activity

If you are going to use Python, open `CM4125_Lab4.ipynb` using [Google Colab](https://colab.research.google.com/drive/1iuDW0B9ja6JUJ2NzKBLpMMiAOjCmzG-Y?usp=sharing) and follow the steps.

Or, you can read `CM4125_Lab4_guided.html` to follow the logic used on the data.
    
* Try to replicate the steps in your preferred tool!